create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('user', 'ai')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists memories (
  id bigint generated by default as identity primary key,
  kind text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists news_bank (
  id bigint generated by default as identity primary key,
  title text not null,
  source text not null default '',
  link text not null default '',
  summary text not null,
  spoken boolean not null default false,
  created_at timestamptz not null default now()
);

-- Auto delete news older than 1 day (run via scheduled function or app logic)
-- News bank RLS
alter table news_bank enable row level security;

drop policy if exists "allow public insert news_bank" on news_bank;
create policy "allow public insert news_bank"
on news_bank for insert to anon with check (true);

drop policy if exists "allow public read news_bank" on news_bank;
create policy "allow public read news_bank"
on news_bank for select to anon using (true);

drop policy if exists "allow public update news_bank" on news_bank;
create policy "allow public update news_bank"
on news_bank for update to anon using (true);

drop policy if exists "allow public delete news_bank" on news_bank;
create policy "allow public delete news_bank"
on news_bank for delete to anon using (true);

alter table memories enable row level security;

drop policy if exists "allow public insert memories" on memories;
create policy "allow public insert memories"
on memories for insert to anon with check (true);

drop policy if exists "allow public read memories" on memories;
create policy "allow public read memories"
on memories for select to anon using (true);
