create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('user', 'ai')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists memories (
  id bigint generated by default as identity primary key,
  kind text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table memories enable row level security;

drop policy if exists "allow public insert memories" on memories;
create policy "allow public insert memories"
on memories for insert to anon with check (true);

drop policy if exists "allow public read memories" on memories;
create policy "allow public read memories"
on memories for select to anon using (true);
