create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('user', 'ai')),
  content text not null,
  created_at timestamptz not null default now()
);
