[phases.setup]
nixPkgs = ["python311", "gcc", "cmake"]
aptPkgs = ["libgomp1"]

[phases.install]
cmds = [
  "cd backend && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "cd backend && python start.py"
