[phases.setup]
nixPkgs = ["python311", "gcc", "cmake"]
aptPkgs = ["libgomp1"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt",
  "pip install --no-cache-dir ./anta-jarvis[server,inference-cloud]"
]

[start]
cmd = "python start.py"
